services:
  - type: web
    name: websoroban-backend
    env: node
    rootDir: backend
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: MONGODB_URI
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    branch: main
    plan: starter 